### ISSUE TITLE
[Flatten Selection to Bitmap] Scale not accurate with out-of-selection effects

### ISSUE THREAD

**Issue by vorbei** [yuanqing/figma-plugins#11]
If the selection contains effects like "Drop Shadow", outside stroke, etc. This plugin will resize bitmap to the exact height/width to Figma's dimensions, and will hence 'scale down' the bitmap a little bit.

Don't know if there are any workarounds in Figma API, but hopefully the plug in can solve this one day.

**Comment by yuanqing** [comment]
Thanks @vorbei for reporting this. Just published a fix to solve this. The **dimension** of the resulting image should be correct now – but the **position** *might* change if there’s a stroke or effect
