### ISSUE TITLE
Sort Layers: Improve logic for numbered frame names

### ISSUE THREAD

**Issue by kupe517** [yuanqing/figma-plugins#12]
Currently if I name my frames with a prepended number like `1 Home` , `2 About`, and the order becomes incorrect at double digits. So once I get to `10 What We Do` it places it after `1 Home` when the plugin runs. 

This could be solved with some additional logic to determine if the first few characters are integers and then doing some comparison logic. 

Great plugin and thanks for you work on it!

**Comment by yuanqing** [comment]
Fixed as of Version 13 of the plugin
