### ISSUE TITLE
Flatten Selection to Bitmap: Image is too large

### ISSUE THREAD

**Issue by davo** [yuanqing/figma-plugins#19]
Figma won't raster when the scale multiplier results in widths / heights over 4096.2.

>> Flatten @ 3x with a frame @ 1365x1365 
<img width="1478" alt="Screen Shot 2020-09-15 at 5 02 26 PM" src="https://user-images.githubusercontent.com/76307/93265389-936fca00-f776-11ea-893a-2a767c03b228.png">

>> Flatten @ 3x with a frame @ 1366x1366 
<img width="1478" alt="Screen Shot 2020-09-15 at 5 02 40 PM" src="https://user-images.githubusercontent.com/76307/93265605-d631a200-f776-11ea-88e4-bb3b32b9e4c0.png">

**Comment by davo** [comment]
Hey @yuanqing will it help to talk about some potential solutions for this bug? I want to take a stab at the issue but I'd like your opinion about which direction seems more feasible.

First, from what I gather Figma states the limits of the `createImage` method regarding [image max size](https://www.figma.com/plugin-docs/api/properties/figma-createimage/#remarks). They are following a common best practice for universal supported limits, in which textures using `texImage2D` **should not** go over 4096. Source: [MDN WebGL best practices](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#know_your_limits_and_extensions).

So, here are some potential scenarios:

- [ ] So, here we are using the Bitmap resolution settings and the dimensions of the selected node. It might possible to calculate the final scaled-up size of the image. So, if the number goes over 4096, this might be resolved by:

	- **A.** Fixing the broken promise: An additional condition is set right before the [selection check](https://github.com/yuanqing/figma-plugins/blob/290df9ebe7f44f30d02a4f62e29e6f18b421b686/packages/figma-flatten-selection-to-bitmap/src/flatten-selection-to-bitmap/main.ts#L15), so the promise does not try to execute `createImageFromGroupAsync`. 
If the condition is faulty, it sends an error message: `Cannot raster selection at ${settings.resolution}. Scaled size ${estimatedSize.width, estimatedSize.height}, exceeds limit.`

	- **B.** Trying to run `createImageFromGroupAsync` at a smaller scale: An additional condition is set right before the [selection check](https://github.com/yuanqing/figma-plugins/blob/290df9ebe7f44f30d02a4f62e29e6f18b421b686/packages/figma-flatten-selection-to-bitmap/src/flatten-selection-to-bitmap/main.ts#L15), but in this case the plugin will recalculate if overriding the resolution from the settings to a lesser scale will exceed the limit of 4096. If not, it will continue the promise and  flag that the resolution was changed. The success message could indicate: `Flattened at ${resolution}x to avoid the canvas limit`.

- [ ] Ok, here is a more complex scenario, this one will require more work. After exploring the [GET image](https://www.figma.com/developers/api#get-images-endpoint) endpoint and testing it with a nodes with sizes 1024 and 2048 and scaling from 1 to 4, I can confirm that the API allows to scale beyond this limit. This offers great possibilities with more complexity, of course. The response time of rastering from the API will increase proportionally as the dimensions and scales go up. 
Questions from this scenario:
	- Could it be possible to raster a node with the API, and right after insert that blob back to the canvas using the methods you created on [Insert Big Image](https://github.com/yuanqing/figma-plugins/tree/main/packages/figma-insert-big-image)?
	- Will this require users adding their own personal tokens for the plugin to fetch images? Personally, I wouldn't mind.  

Here are are the rasters from the the GET image endpoint. 

| File / Scale | 2x | 3x | 4x |
|:--|:--|:--|:--|
| 1024 | ![Image](https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/8fb0/6391/07325a55b2bd916dcb8babc109cc017d) | ![Image](https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/32fc/0aea/34d670aec33f3ca7e98e9fc08a7dff15) | ![Image](https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/bfed/3cd9/35e48e292d027529efe62b28b9b826a2) |
| 2048 | ![Image](https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/94b6/2cc4/e90da66fa0f7e692c460926b447591f6) | ![Image](https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/94b6/2cc4/e90da66fa0f7e692c460926b447591f6) | ![Image](https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/94b6/2cc4/e90da66fa0f7e692c460926b447591f6) |

Figma API Docs for reference:
<img width="751" alt="Screen Shot 2021-04-02 at 3 29 37 PM" src="https://user-images.githubusercontent.com/76307/113448284-89877e80-93c9-11eb-8aba-d7382d8ab609.png">

PNG downloaded from the Endpoint
<img width="906" alt="Screen Shot 2021-04-02 at 3 30 51 PM" src="https://user-images.githubusercontent.com/76307/113448948-cdc74e80-93ca-11eb-842c-300d13a009f4.png">

**Comment by yuanqing** [comment]
@davo

> raster a node with the API, and right after insert that blob back to the canvas using the methods you created on Insert Big Image

Thanks for the detailed write-up! I quickly looked into this today and it turned out to be a small change because most of the implementation is already done in Insert Big Image – d474401

**Comment by yuanqing** [comment]
Just published a new version of the plugin to Figma. It’ll take some time to run if you have a large selection or when flattening at a high resolution

**Comment by davo** [comment]
Thanks @yuanqing! I'm glad it the write-up helped in any way.

Amazed by the PR with `63 additions and 69 deletions`, and the fact that you are achieving this level of reusability between your own work 👏🏼
