### ISSUE TITLE
Smart Sort Layers: Fixed and Scroll Elements

### ISSUE THREAD

**Issue by bansalsohil** [yuanqing/figma-plugins#21]
Smart sort doesn't take into consideration fixed and scroll elements within a frame and converts scroll elements into fixed elements

**Comment by yuanqing** [comment]
@bansalsohil – Thanks for reporting this! Just shipped a fix which is now live in the Figma plugin directory. Do consider sponsoring my open source work if you find my Figma plugins useful for you
