### ISSUE TITLE
[Feature request] Move Layers: Insert math operation and its result as an input

### ISSUE THREAD

**Issue by RukmaPratista** [yuanqing/figma-plugins#23]
Hi, I use Move Layers regularly, and it's been helpful. I hope you can consider to update it so we can use simple arithmetic operation, just like how Figma and Adobe Illustrator handle math operations in their coordinate input field. Thank you.

**Comment by yuanqing** [comment]
@RukmaPratista Thanks for reporting this.

The plugin already does support basic arithmetic input. It could be a bug that’s causing it to not work for you – it would help if you shared more details about:

1. the arithmetic expression that didn’t work and
2. the web browser that you used

**Comment by RukmaPratista** [comment]
Aaah, my fault, I thought it still doesn't support math operation. I've been using it regularly without knowing that math operation has been supported. I'll close this issue, sorry.
