### ISSUE TITLE
can not use enablePrivatePluginApi property in manifest.json

### ISSUE THREAD

**Issue by BFridge** [yuanqing/figma-plugins#30]
enablePrivatePluginApi?: boolean
This enables API that's specific to private plugins. Setting this will also enable local plugins to work with these APIs during development.

 how can  I use this property ?  
 is there a way to skip the generate of  manifest.json when run build? 

thx

**Comment by yuanqing** [comment]
> enablePrivatePluginApi?: boolean

This option will be supported in the next stable release of the `build-figma-plugin` CLI

**Comment by yuanqing** [comment]
Closing given the release of `@create-figma-plugin/build@1`
