### ISSUE TITLE
Clean Document: Deleting layer flexibility

### ISSUE THREAD

**Issue by allanpmaltais** [yuanqing/figma-plugins#7]
Hey 👋

Apologies for posting a question here. Happy to reach out elsewhere if you prefer. Just point me in the right direction.

---

My team was looking at using Clean Document for a project and wondering if there's a way to avoid deleting all hidden layers. 

The cases where this is most prominent are assets with multiple states that we need to show and hide (some elements will be hidden based on the displayed state). Let me know if there's anything we can do to avoid clearing those all out.

Thanks in advance!

**Comment by yuanqing** [comment]
Currently, the only way is to run the command without checking the “Delete hidden layers” checkbox. The plugin does not allow for hidden layers to be retained on a ”per-layer“ basis

**Comment by yuanqing** [comment]
Related to https://github.com/yuanqing/figma-plugins/issues/6

**Comment by yuanqing** [comment]
The Clean Layers command now provides an option to **Skip locked layers**. If this option is checked, locked layers (and all their nested children) will be skipped from processing.
